name: Compile and test SymCC
on: [pull_request, workflow_dispatch]
jobs:
  llvm_compatibility:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        llvm_version: [11, 12, 13, 14, 15]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-${{ matrix.llvm_version }}-dev \
            libz3-dev \
      - name: Build SymCC with the QSYM backend
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DZ3_TRUST_SYSTEM_VERSION=ON \
            -DQSYM_BACKEND=ON \
            -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm_version }}/cmake \
            ..
          make
  llvm_compatibility_latest_llvm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        llvm_version: [16, 17]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add LLVM project deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ matrix.llvm_version }} main
          repo-name: llvm
          update: false
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-${{ matrix.llvm_version }}-dev \
            libz3-dev \
      - name: Build SymCC with the QSYM backend
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DZ3_TRUST_SYSTEM_VERSION=ON \
            -DQSYM_BACKEND=ON \
            -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm_version }}/cmake \
            ..
          make

  # 1- only push to DockerHub from the master/main branch and from original repository
  # Although you can remove the if statements to test on a fork if needed.
  # 2- I figure we should only push if all other tests pass
  upload_dockerhub:
    if: github.repository == 'eurecom-s3/symcc' && github.ref == 'refs/heads/master'
    needs: [ llvm_compatibility, llvm_compatibility_latest_llvm ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/symcc:latest